/** Server-side diagnostic logs (English for supportability) */
export const serverLog = {
  dbDir: (path: string) => console.log("[DB] directory:", path),
  ossDir: (path: string) => console.log("[OSS] directory:", path),
  skillsDir: (path: string) => console.log("[Skills] directory:", path),
  assetsDir: (path: string) => console.log("[Assets] directory:", path),
  webDir: (path: string) => console.log("[Web] static directory:", path),
  webDirMissing: (path: string) => console.warn("[Web] static directory missing:", path),
  serverStarted: (port: number | string) => console.log(`[Server] started http://localhost:${port}`),
  serverClosed: () => console.log("[Server] stopped"),
  env: (env: string | undefined) => console.log(`[Env] NODE_ENV=${env ?? "undefined"}`),
  socketNs: (name: string) => console.log(`[Socket] namespace registered: /api/socket/${name}`),
  agentConnected: (agent: string, id: string) => console.log(`[${agent}] connected:`, id),
  agentDisconnected: (agent: string, id: string) => console.log(`[${agent}] disconnected:`, id),
  agentAuthFailed: (agent: string) => console.log(`[${agent}] connection failed: invalid token`),
  agentMissingKey: (agent: string) => console.log(`[${agent}] connection failed: missing isolationKey`),
  agentContextUpdated: (agent: string, key: string) => console.log(`[${agent}] context updated:`, key),
  agentThinkConfig: (agent: string, cfg: unknown) => console.log(`[${agent}] think config updated:`, cfg),
  initDbRecreate: (name: string) => console.log("[InitDB] recreated table:", name),
  initDbCreate: (name: string) => console.log("[InitDB] created table:", name),
  initDbSeed: (name: string) => console.log("[InitDB] seeded table:", name),
  projectOssDeleted: (id: number) => console.log(`[Project] OSS folder deleted for project ${id}`),
  projectOssSkipped: (id: number) => console.log(`[Project] no OSS folder for project ${id}, skipped`),
  ossThumbFail: (e: unknown) => console.warn("[OSS] thumbnail generation failed:", e),
  bindAudioFail: (assetId: number, e: unknown) => console.error(`[bindAudio] asset ${assetId} failed:`, e),
  extractAssetsFail: (group: string, e: unknown) => console.error(`[extractAssets] group=[${group}] failed:`, e),
  deleteManualFail: (dir: string, e: unknown) => console.error("[Delete visual manual] failed:", dir, e),
  saveFlowSortFail: (e: unknown) => console.error("[SaveFlow] storyboard sort update failed", e),
};
